revert skipped build stages

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,26 +25,26 @@
 						"github-token": "${{ secrets.GITHUB_TOKEN }}"
 					}
 				},
-				#{ TODO
-				#	"if": "matrix.os == 'ubuntu-latest'",
-				#	"name": "Test docker",
-				#	"run":
-				#	"
-				#		docker --version \n
-				#		docker build . -t sy \n
-				#		docker run --entrypoint syntran sy --version \n
-				#		docker run sy --version # syntran is already the default entrypoint \n
-				#		docker run sy -c \"1 + 2;\" \n
-				#		ans=$(docker run sy -c \"1 + 2;\") \n
-				#		if [[ \"$ans\" == \" ans = \\`3\\`\" ]] ; then \n
-				#			echo \"win\" \n
-				#			exit 0 \n
-				#		else \n
-				#			echo \"fail\" \n
-				#			exit 1 \n
-				#		fi \n
-				#	"
-				#},
+				{
+					"if": "matrix.os == 'ubuntu-latest'",
+					"name": "Test docker",
+					"run":
+					"
+						docker --version \n
+						docker build . -t sy \n
+						docker run --entrypoint syntran sy --version \n
+						docker run sy --version # syntran is already the default entrypoint \n
+						docker run sy -c \"1 + 2;\" \n
+						ans=$(docker run sy -c \"1 + 2;\") \n
+						if [[ \"$ans\" == \" ans = \\`3\\`\" ]] ; then \n
+							echo \"win\" \n
+							exit 0 \n
+						else \n
+							echo \"fail\" \n
+							exit 1 \n
+						fi \n
+					"
+				},
 				{
 					"if": "matrix.os == 'ubuntu-latest'",
 					"name": "Set ubuntu PATH",
@@ -59,6 +59,8 @@
 					},
 					"run":
 					"
+						gfortran --version \n
+
 						fpm install
 						  --profile release
 						  --link-flag '-static-libgcc -static-libgfortran'
@@ -77,8 +79,7 @@
 						#ls /lib/x86_64-linux-gnu/ \n
 						#ls /lib/ \n
 
-						# TODO \n
-						exit 0 \n
+						#exit 0 \n
 
 						chmod +x ./samples/shebang.syntran \n
 						./samples/shebang.syntran \n
