update binary install doc per release 0.0.48

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -26,27 +26,6 @@
 					}
 				},
 				{
-					# TODO: add a stage to test the binary dockerfiles in the docker dir
-					"if": "matrix.os == 'ubuntu-latest'",
-					"name": "Test docker",
-					"run":
-					"
-						docker --version \n
-						docker build . -t sy \n
-						docker run --entrypoint syntran sy --version \n
-						docker run sy --version # syntran is already the default entrypoint \n
-						docker run sy -c \"1 + 2;\" \n
-						ans=$(docker run sy -c \"1 + 2;\") \n
-						if [[ \"$ans\" == \" ans = \\`3\\`\" ]] ; then \n
-							echo \"win\" \n
-							exit 0 \n
-						else \n
-							echo \"fail\" \n
-							exit 1 \n
-						fi \n
-					"
-				},
-				{
 					"if": "matrix.os == 'ubuntu-latest'",
 					"name": "Set ubuntu PATH",
 					"run": "echo \"$HOME/bin\" >> $GITHUB_PATH"
@@ -102,6 +81,27 @@
 						#"path": "/home/runner/bin/syntran",
 						"name": "syntran-linux"
 					}
+				},
+				{
+					# TODO: add a stage to test the binary dockerfiles in the docker dir
+					"if": "matrix.os == 'ubuntu-latest'",
+					"name": "Test docker",
+					"run":
+					"
+						docker --version \n
+						docker build . -t sy \n
+						docker run --entrypoint syntran sy --version \n
+						docker run sy --version # syntran is already the default entrypoint \n
+						docker run sy -c \"1 + 2;\" \n
+						ans=$(docker run sy -c \"1 + 2;\") \n
+						if [[ \"$ans\" == \" ans = \\`3\\`\" ]] ; then \n
+							echo \"win\" \n
+							exit 0 \n
+						else \n
+							echo \"fail\" \n
+							exit 1 \n
+						fi \n
+					"
 				},
 				{
 					"if": "matrix.os == 'ubuntu-latest'",
