add rocky build stage

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -259,6 +259,33 @@
 			#},
 		]
 	},
+	"build-rocky": {
+		# Build and package syntran from source in rocky linux Dockerfile
+		"name": "Build on rocky linux",
+		"runs-on": "ubuntu-latest",
+		"steps": [
+			{"uses": "actions/checkout@v1"},
+			{
+				"name": "Build docker",
+				"run":
+				"
+					docker --version \n
+					docker build . --file Dockerfile.rocky -t sy \n
+					docker run --entrypoint syntran sy --version \n
+					docker run sy --version # syntran is already the default entrypoint \n
+					docker run sy -c \"1 + 2;\" \n
+					ans=$(docker run sy -c \"1 + 2;\") \n
+					if [[ \"$ans\" == \" ans = \\`3\\`\" ]] ; then \n
+						echo \"win\" \n
+						exit 0 \n
+					else \n
+						echo \"fail\" \n
+						exit 1 \n
+					fi \n
+				"
+			},
+		]
+	},
 	"test-gfortran": {
 		"name": "Test with gfortran-${{ matrix.gfortran }}",
 		"runs-on": "${{ matrix.os }}",
